# Generated by Django 6.0.5 on 2026-05-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrapeVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ყურძნის ჯიში")),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="რეგიონი")),
            ],
        ),
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="სახელწოდება")),
                ("description", models.TextField(verbose_name="აღწერა")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="ფასი"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("RED", "წითელი"),
                            ("WHITE", "თეთრი"),
                            ("ROSE", "ვარდისფერი"),
                            ("AMBER", "ქარვისფერი/ქვევრის"),
                        ],
                        max_length=10,
                        verbose_name="ფერი",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="wines/", verbose_name="სურათი"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grape_variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wines",
                        to="wines.grapevariety",
                        verbose_name="ჯიში",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wines",
                        to="wines.region",
                        verbose_name="რეგიონი",
                    ),
                ),
            ],
        ),
    ]
